-- Andrian Tambunan
-- Anas Azhar
-- Ilham Insan Wafi
-- Muhammad Daffa Ashdaqfillah

-- create user
CREATE USER kasir WITH PASSWORD 'kasir123';
CREATE USER pemasok WITH PASSWORD 'pemasok123';
CREATE USER manager WITH PASSWORD 'manager123';

-- kasir access
GRANT SELECT, INSERT, UPDATE ON TRANSAKSI, TRANSAKSI_DETAIL TO kasir;
GRANT SELECT, INSERT, UPDATE ON MEMBER TO kasir;
GRANT SELECT ON BARANG, RAK_GUDANG, RAK_GUDANG_DETAIL, KODE_TRANSAKSI, DISKON TO kasir;

-- pemasok access
GRANT SELECT, INSERT, UPDATE ON BARANG TO pemasok;

-- manager access
GRANT SELECT, INSERT, UPDATE ON KASIR TO manager;
GRANT SELECT, INSERT, UPDATE ON PEMASOK TO manager;
GRANT SELECT ON TRANSAKSI, TRANSAKSI_DETAIL, PELANGGAN, RAK_GUDANG, RAK_GUDANG_DETAIL, KODE_TRANSAKSI, BARANG, DISKON TO manager;

CREATE TABLE MEMBER(   
    M_NO CHAR(10) NOT NULL PRIMARY KEY,   
    M_NAMA VARCHAR(30),   
    M_JENISKEL CHAR(1),   
    M_TEMPATLAHIR VARCHAR(20),     
    M_TANGGALLAHIR DATE,     
    M_TANGGALDAFTAR DATE,  
    M_ALAMAT VARCHAR(50),     
    M_EMAIL VARCHAR(30),  
    M_PASSWORD VARCHAR(32), 
    M_NOTELP VARCHAR(13)  
    );
	
CREATE TABLE KASIR(  
    K_NO CHAR(2) NOT NULL PRIMARY KEY,  
    K_NAMA VARCHAR(30) NOT NULL,  
    K_ALAMAT VARCHAR(50) NOT NULL,  
    K_NOTELP VARCHAR(13) NOT NULL, 
    K_TGLMASUK DATE NOT NULL,  
    K_EMAIL VARCHAR(50) NOT NULL,  
    K_PASSWORD VARCHAR(20) NOT NULL, 
    K_TGLLAHIR DATE NOT NULL
    );
	
CREATE TABLE TRANSAKSI(   
    T_NO INT NOT NULL PRIMARY KEY,   
    T_ISCASHLESS CHAR(1) NOT NULL, 
    T_TGLPEMBELIAN TIMESTAMP NOT NULL,
    MEMBER_M_NO CHAR(10) NOT NULL,  
    FOREIGN KEY (MEMBER_M_NO) REFERENCES MEMBER(M_NO)   
    );
	

CREATE TABLE BARANG(   
    B_ID VARCHAR(5) NOT NULL PRIMARY KEY,   
    B_NAMA VARCHAR(50) NOT NULL,   
    B_HARGA DECIMAL(10,2) NOT NULL,
	B_STOK INT NOT NULL
    );

CREATE TABLE KASIR_DETAIL(  
    KD_NO INT NOT NULL PRIMARY KEY,  
    KASIR_K_NO CHAR(2) NOT NULL,  
    TRANSAKSI_T_NO INT NOT NULL,  
    FOREIGN KEY (KASIR_K_NO) REFERENCES KASIR(K_NO),  
    FOREIGN KEY (TRANSAKSI_T_NO) REFERENCES TRANSAKSI(T_NO)  
    );
	
CREATE TABLE TRANSAKSI_DETAIL(   
    TD_NO INT NOT NULL PRIMARY KEY,   
    TD_BANYAK_BARANG INT NOT NULL,   
    TRANSAKSI_T_NO INT NOT NULL,   
    BARANG_B_ID VARCHAR(5) NOT NULL, 
    FOREIGN KEY (TRANSAKSI_T_NO) REFERENCES TRANSAKSI(T_NO),  
    FOREIGN KEY (BARANG_B_ID) REFERENCES BARANG(B_ID)  
    );

CREATE TABLE RAK_GUDANG( 
    G_KODERAK INT NOT NULL PRIMARY KEY, 
    G_NAMA VARCHAR(20) NOT NULL, 
    G_ISFULL CHAR(1) NOT NULL 
	);

CREATE TABLE DISKON( 
    D_NO CHAR(3) NOT NULL PRIMARY KEY, 
    D_NAMA VARCHAR(60) NOT NULL, 
    D_DISKON DECIMAL(10, 2) NOT NULL, 
    BARANG_B_ID VARCHAR(5) NOT NULL, 
    FOREIGN KEY (BARANG_B_ID) REFERENCES BARANG(B_ID) 
	);

CREATE TABLE RAK_GUDANG_DETAIL( 
    GD_NO INT NOT NULL PRIMARY KEY, 
    RAK_GUDANG_G_KODERAK INT NOT NULL, 
    BARANG_B_ID VARCHAR(5) NOT NULL, 
    FOREIGN KEY (RAK_GUDANG_G_KODERAK) REFERENCES RAK_GUDANG(G_KODERAK), 
    FOREIGN KEY (BARANG_B_ID) REFERENCES BARANG(B_ID) 
	);
	
CREATE TABLE PEMASOK( 
    PEM_NO INT NOT NULL PRIMARY KEY, 
    PEM_PERUSAHAAN VARCHAR(30) NOT NULL, 
    PEM_NOTELP VARCHAR(15) NOT NULL, 
    PEM_ALAMAT VARCHAR(40) NOT NULL, 
    RAK_GUDANG_G_KODERAK INT NOT NULL,
    FOREIGN KEY (RAK_GUDANG_G_KODERAK) REFERENCES RAK_GUDANG(G_KODERAK)
    );

CREATE TABLE KODE_TRANSAKSI ( 
    KT_ID INT NOT NULL PRIMARY KEY, 
    KT_BARCODE VARCHAR(13), 
    KT_KADALUARSA DATE, 
    BARANG_B_ID VARCHAR(5) NOT NULL, 
    FOREIGN KEY (BARANG_B_ID) REFERENCES BARANG(B_ID) 
	);
